version: "3.9"


services:
  database:
    image: postgres:latest
    environment:
     - POSTGRES_DB=Hookah
     - POSTGRES_USER=username
     - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    expose:
      - 5432